### ISSUE TITLE
Constant session flushes on Heroku

### ISSUE THREAD

**Issue by SergiiShcherbak** [mxsasha/django-restricted-sessions#13]
RestrictedSessionsMiddleware causes constant logouts on Heroku, sometimes immediately after logging in. Disabling the middleware fixed the issue.

Note: the issue does not occur in local development, only in production.

My settings.py:
`RESTRICTEDSESSIONS_AUTHED_ONLY = True`

**Comment by erikr** [comment]
This is most likely because the IP you're getting in `request.META['REMOTE_ADDR']` is a load balancer or something like that at Heroku, not the real client's IP. This can probably be found in [`X_FORWARDED_FOR`](https://stackoverflow.com/questions/18264304/get-clients-real-ip-address-on-heroku), but I'm not sure whether setting `RESTRICTEDSESSIONS_REMOTE_ADDR_KEY` to `X_FORWARDED_FOR` will yield the desired effect - I don't know enough about Heroku setups for that.
